current GPU: NVIDIA A40
using GPU: 2
Traceback (most recent call last):
  File "training.py", line 184, in <module>
    main()
  File "training.py", line 173, in main
    model = MeshProcessingNetwork(**model_params).to(device)
  File "/data2/practical-wise2223/MeshBody/BodyMeshGNN/model.py", line 309, in __init__
    self.gnn = GraphFeatureEncoder(
  File "/data2/practical-wise2223/MeshBody/BodyMeshGNN/model.py", line 253, in __init__
    conv_layers = get_conv_layers(
  File "/data2/practical-wise2223/MeshBody/BodyMeshGNN/model.py", line 44, in get_conv_layers
    conv_layers = [
  File "/data2/practical-wise2223/MeshBody/BodyMeshGNN/model.py", line 45, in <listcomp>
    conv(in_ch, out_ch, **conv_params) for in_ch, out_ch in pairwise(channels)
TypeError: __init__() got an unexpected keyword argument 'num_heads'